- src/glide.lock
- src/glide.yaml
- src/tr1d1um/WDMP_Type.go
- src/tr1d1um/WDMP_test.go
- src/tr1d1um/conversion_utils.go
- src/tr1d1um/conversion_utils_test.go
- src/tr1d1um/http.go
- src/tr1d1um/http_test.go
- src/tr1d1um/tr1d1um.go
- src/tr1d1um/tr1d1um_type.go
Also ran go-fmt on the files: @schmidtw
> Unit test for conversion utilities + Using new validation library

- src/tr1d1um/http.go
- src/tr1d1um/tr1d1um.go
- src/tr1d1um/tr1d1um_test.go
> Misc important fixes

- src/tr1d1um/http.go
- src/tr1d1um/http_test.go
- src/tr1d1um/mocks_test.go
- src/tr1d1um/tr1d1um.go
- src/tr1d1um/tr1d1um_test.go
> Service Validation

- src/glide.lock
- src/glide.yaml
- src/tr1d1um/conversion_utils.go
- src/tr1d1um/http.go
- src/tr1d1um/http_test.go
- src/tr1d1um/mocks_test.go
- src/tr1d1um/tr1d1um.go
- src/tr1d1um/tr1d1um_response.go
- src/tr1d1um/tr1d1um_response_test.go
- src/tr1d1um/tr1d1um_test.go
> Client timeouts should trigger 503 status code in responses from TR1D1UM

- src/tr1d1um/http.go
- src/tr1d1um/http_test.go
- src/tr1d1um/tr1d1um.go
A way to answer the following questions:
- what release of Tr1d1um is this VM running? `release` header value
- what is the hostname of this machine? `hostname` header value
> Forward machine / release in header values

- src/glide.lock
- src/glide.yaml
- src/tr1d1um/http.go
- src/tr1d1um/tr1d1um.go
> Feature/prometheus endpoint (WIP)

- src/glide.lock
- src/glide.yaml
- src/tr1d1um/http.go
- src/tr1d1um/tr1d1um.go
Reverts Comcast/tr1d1um#31 in favor of adding a common `webpa-common/server`
> Revert "Feature/prometheus endpoint (WIP)"

- src/tr1d1um/communication.go
- src/tr1d1um/communication_test.go
> Close response body after reading it

- README.md
The following badges have been added.
Please review.
> Adds badges to README for Code Climate and Release version [closes #125]

- .gitignore
- Makefile
- deploy/Dockerfile
- deploy/Dockerfile.local
- main.go
> implemented dynamic versioning

- release_notes.md
- translation/transport.go
- translation/transport_test.go
Solves [#101](https://github.com/xmidt-org/tr1d1um/issues/110)
> Remove temporary `/iot` endpoint

- CHANGELOG.md
- translation/transport.go
- translation/transport_test.go
- translation/transport_utils.go
- translation/transport_utils_test.go
fixes 
[https://github.com/xmidt-org/tr1d1um/issues/139](url)
> made changes to transport.go decodeRequest

- Dockerfile
- Makefile
- deploy/packaging/tr1d1um_spruce.yaml
- go.mod
- go.sum
- tr1d1um.yaml
> fix docker building and spruce configuration

- CHANGELOG.md
- go.mod
- go.sum
- main.go
In this PR I had covered webhook endpoints for open telemetry.
> updated Ancla version

- .golangci.yaml
- main.go
- primaryHandler.go
- stat/endpoint.go
fixes https://github.com/xmidt-org/tr1d1um/issues/240
> fixed lint issues

- go.mod
- go.sum
- stat/transport.go
- transaction/context.go
- transaction/errors_test.go
- transaction/transactor.go
- transaction/transactor_test.go
- translation/transport.go
- translation/transport_utils.go
fixes https://github.com/xmidt-org/tr1d1um/issues/260
> getting rid of transaction logger

- CHANGELOG.md
- Uber fx integration
- closes https://github.com/xmidt-org/tr1d1um/issues/288
- closes https://github.com/xmidt-org/tr1d1um/issues/291
> Uber FX Integration Release v0.7.7

- CHANGELOG.md
- Add support for an alternate server https://github.com/xmidt-org/tr1d1um/pull/297
> Uber FX Alternate Server Release v0.7.8

- CHANGELOG.md
- [`/api/v2/device/ 500 EOF Error #328](https://github.com/xmidt-org/tr1d1um/issues/328)
- [Remove nonstandard charset for media type JSON encodings #336](https://github.com/xmidt-org/tr1d1um/issues/336)
- [Create TransactionUUID if not provided #334](https://github.com/xmidt-org/tr1d1um/issues/334)
> Release: v0.7.12

- CHANGELOG.md
- auth.go
- tr1d1um.yaml
> Fix jwtValidator unpacking

- CHANGELOG.md
- go.mod
- go.sum
- primaryHandler.go
> Bug: Add ancla watcher to fx lifecycle

- CHANGELOG.md
Release branch for following changes:
https://github.com/xmidt-org/tr1d1um/pull/385
https://github.com/xmidt-org/tr1d1um/pull/386
> 0.8.5 Release

- CHANGELOG.md
Release for working tracing: #389
> 0.9.0 Release

- CHANGELOG.md
- translation/transport.go
> patch: Device level 403 errors are not properly propagated

- .github/workflows/ci.yml
docker will be disable while issues in multi platform builds are resolved #618
> chore: temporary disable docker #618

- Dockerfile
Forgot in my `shared-go` testing that I skipped `PLATFORM`-specific `FROM`s
> patch dockerfile with fixes for new new shared-go
