- src/glide.lock
- src/tr1d1um/communication.go
- src/tr1d1um/communication_test.go
- src/tr1d1um/conversion_utils.go
- src/tr1d1um/conversion_utils_test.go
- src/tr1d1um/http.go
- src/tr1d1um/http_test.go
- src/tr1d1um/mocks_test.go
- src/tr1d1um/tr1d1um.go
- src/tr1d1um/tr1d1um_test.go
- src/tr1d1um/tr1d1um_type.go
- src/tr1d1um/wdmp_type.go
tr1d1um runs locally with these changes.
> Initialization first attempt.

- src/tr1d1um/tr1d1um.go
Without this change, wrp `Source` property is incomplete (current: `[baseSource]/` vs. desired: `[baseSource]/iot`)
> need iot service in path

- CHANGELOG.md
- translation/service.go
- translation/service_test.go
- translation/transport.go
- translation/transport_test.go
- translation/transport_utils.go
- translation/transport_utils_test.go
fixes 
[https://github.com/xmidt-org/tr1d1um/issues/142]
> WRP source

- CHANGELOG.md
- translation/errors.go
- translation/transport.go
- translation/transport_test.go
- translation/transport_utils.go
- translation/transport_utils_test.go
This PR fixes the bug in which tr1d1um responded with a 500 Internal Server error for cases that are clearly user errors:
- Invalid MAC Addresses for device ID
- Invalid Table Row structures for Add and Replace WDMP requests
> Improve user error reporting

- CHANGELOG.md
- go.mod
- go.sum
- main.go
- tr1d1um.yaml
builds off of https://github.com/xmidt-org/webpa-common/pull/459
> added endpoint regex for capabilityCheck metric

- Makefile
- README.md
- deploy/Dockerfile
Resolve #172 using solution from xmidt-org/talaria/pull/150
> Optimize makefile (#172)

- deploy/packaging/tr1d1um.spec
Debugging why copr builds are failing:
```
Writing config into /tmp/copr-rpmbuild-algqo_4b/obtain-sources/.config/rpkg.conf
Running: rpkg srpm --outdir /tmp/copr-rpmbuild-algqo_4b --spec /tmp/copr-rpmbuild-algqo_4b/obtain-sources/tr1d1um/deploy/packaging/tr1d1um.spec
cmd: ['rpkg', 'srpm', '--outdir', '/tmp/copr-rpmbuild-algqo_4b', '--spec', '/tmp/copr-rpmbuild-algqo_4b/obtain-sources/tr1d1um/deploy/packaging/tr1d1um.spec']
cwd: /tmp/copr-rpmbuild-algqo_4b/obtain-sources/tr1d1um
rc: 0
stdout: Wrote: /tmp/copr-rpmbuild-algqo_4b/tr1d1um.spec
stderr: error: /tmp/copr-rpmbuild-algqo_4b/tr1d1um.spec: line 29: %S: argument expected
can't parse specfile
Output: ['tr1d1um.spec']
```
> Copr spec file parser does not like '%S' 

- CHANGELOG.md
- go.mod
- translation/transport.go
- translation/transport_test.go
The direct casting to `[]string` was failing because the partnerIDs list is of type `[]interface{}` internally. This is an issue @kristinaspring already found and fixed in another service recently.
> fix casting bug for fetching partnerIDs

- CHANGELOG.md
- main.go
- primaryHandler.go
fixes https://github.com/xmidt-org/tr1d1um/issues/258
> fix duration for v2 endpoint if needed

- CHANGELOG.md
- Dependency update
- guardrails says github.com/gorilla/websocket v1.5.0 has a high vulnerability but no vulnerabilities have been filed
-  [github.com/gorilla/sessions v1.2.1 cwe-613 no patch available](https://ossindex.sonatype.org/vulnerability/sonatype-2021-4899)
- JWT Migration #289 
- update to use clortho `Resolver` & `Refresher`
- update to use clortho `metrics` & `logging`
- Update ancla client initialization
- Update Config
- Use [uber/zap](https://github.com/uber-go/zap) for clortho logging
- Use [xmidt-org/sallust](https://github.com/xmidt-org/sallust) for the zap config unmarshalling 
- Update auth config for clortho
- Update ancla config
> JWK Migration Release v0.7.6

- CHANGELOG.md
- go.mod
- go.sum
- Patch [#320](https://github.com/xmidt-org/tr1d1um/issues/320)
- General dependency update
closes #320
> Release: Uber fx health port patch

- CHANGELOG.md
- routes.go
> Bug: Fix Metric Server

- CHANGELOG.md
What's include:
- [No Prom Metrics Being Produced #329](https://github.com/xmidt-org/tr1d1um/issues/329)
> Release: Metric Server Patch

- CHANGELOG.md
- Updated tracing configuration documentation in tr1d1um.yaml to reflect changes in Candlelight [#346](https://github.com/xmidt-org/tr1d1um/pull/346)
- [https://github.com/xmidt-org/tr1d1um/issues/340](https://github.com/xmidt-org/tr1d1um/issues/340)
- [v2 & v3 endpoints are not enforcing capabilities xmidt-org/tr1d1um#342](https://github.com/xmidt-org/tr1d1um/issues/342)
- [v3 endpoint is not validating webhooks #341](https://github.com/xmidt-org/tr1d1um/issues/341)
- [8090 support has been removed #343](https://github.com/xmidt-org/tr1d1um/issues/343)
- [Remove Deprecated webpa-common #304](https://github.com/xmidt-org/tr1d1um/issues/304)
closes #343
closes #342 
closes #341 
closes #340
closes #304
> Release: v0.8.0

- CHANGELOG.md
- [Replace go-kit/kit/log & go-kit/log with zap #356](https://github.com/xmidt-org/tr1d1um/pull/356)
closes #355
> Release: v0.8.1

- CHANGELOG.md
- [Fix jwtValidator & capabilityCheck config unpacking #359](https://github.com/xmidt-org/tr1d1um/issues/359)
closes #359
> Release: v0.8.2

- CHANGELOG.md
- go.mod
- go.sum
- translation/transport.go
- translation/transport_test.go
- [Tr1d1um Panic: device status code used as the response status code can cause an unrecoverable panic #354](https://github.com/xmidt-org/tr1d1um/issues/354)
> Bug: Limit device status codes used as tr1d1um's resp status code

- CHANGELOG.md
- [Bug: Event related metrics fail to update #361](https://github.com/xmidt-org/tr1d1um/issues/361)
- [Tr1d1um Panic: device status code used as the response status code can cause an unrecoverable panic #354](https://github.com/xmidt-org/tr1d1um/issues/354)
closes #354
closes #361
> Release: v0.8.3

- CHANGELOG.md
- translation/transport.go
- Realized I used `tracestatus` instead of the correct W3C standard header, `tracestate`. This has been corrected.
- Validated that `traceparent` can exist without a `tracestate` but not vice versa. We decided that if a `tracestate` is not passed, we will still set the `tracestate` header in WRP with an empty value. The logic has been updated to match these discoveries/decisions.
> Tracing Header Patch

- Dockerfile
This PR updates `FROM` in the `Dockerfile` to include `--platform=linux/$ARCH`.
The current runs error out (https://github.com/xmidt-org/tr1d1um/actions/runs/13448107751) due to an `arm64` `buildx` directive disagreeing with the non-platformed `FROM`, which I believe needs additional configuration.
https://docs.docker.com/build/building/multi-platform/#cross-compilation
> update FROM to use --platform=linux/$ARCH

- go.mod
- main.go
- metrics.go
- primaryHandler.go
service_configs_retries will count retries for the following xmidt service configs api calls:
- `/device`
- `/device/${device}/stat`
> feat: add service_configs_retries metrics for outbound xmidt calls

- .github/workflows/ci.yml
docker builds will be enable for amd64 and disabled for arm64 #618
> chore: enable docker builds only for amd64 #618
